### ISSUE TITLE
太棒了！

### ISSUE THREAD

**Issue by Amonidi** [asteltis/grayscale-check#1]
非常感谢作者，方便了不少！就是框选窗口、显示窗口大小、延时设置这些功能如果能记忆上次设置就更好了！另外如果延时功能再有更小的数值的话，那将是完美！总之现在就够用了，感谢作者！

**Comment by asteltis** [comment]
非常感谢你的使用和反馈！开发这个软件也是因为自己学画的时候想着“如果有这样的功能就好了”。很高兴能帮到你。
1.记忆设置：确实是一个很重要的功能，我会在更新中加入这个功能。
2.延时设置：当时加这个功能是为了适应不同配置的电脑，1.1版本最小值从0.1s调到了0.02s。
如果你有更多的想法或问题，欢迎随时提出！
目前更新了1.1版本
https://github.com/asteltis/grayscale-check/releases/tag/v1.1
